server:
  port: 8081

spring:
  application:
    name: CYBERSOCIETY
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/cyber
    password: befoyda
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  sql:
    init:
      mode: never
      continue-on-error: true
  main:
    lazy-initialization: true

  servlet:
    multipart:
      max-file-size: 20MB
  jackson:
    date-format: yyyy-MM-dd
